"""
Price augmentation script for view_inventory.json and view_purchases.json.

Adds representative prices to inventory and purchase records based on
product type, brand, and ingredient category.

Generated by Gemini, reviewed and applied by Claude.
"""
import json
import os

# 1. REPRESENTATIVE PRICE SEED DATA
# Prices are "Package Prices" (unit_price/unit_cost)
PRICE_MAP = {
    "staples": {"default": 5.49, "flour": 5.99, "sugar": 4.50, "salt": 3.25, "yeast": 8.99, "cornstarch": 2.25},
    "premium_brands": {
        "callebaut": {"10.0:kg": 245.00, "2.5:kg": 68.00, "default": 25.00},
        "valrhona": 45.00,
        "nielsen-massey": 35.00,
        "heilala": 55.00,
        "cointreau": 38.00,
        "chambord": 24.00,
        "penzeys": 14.50,
        "king arthur": 7.49,
        "bob's red mill": 9.99
    },
    "categories": {
        "extract": 14.00,
        "oil_olive": 28.00,
        "butter": 5.99, # Price per lb/package
        "nuts": 18.99,
        "spirits": 18.00
    }
}

def get_seed_price(record):
    slug = record.get('product_slug', '').lower()
    brand = str(record.get('brand', '')).lower()
    ingredient = record.get('ingredient_name', '').lower()

    # Check Premium Brands first
    for b, price in PRICE_MAP['premium_brands'].items():
        if b in brand:
            if isinstance(price, dict):
                for detail, p in price.items():
                    if detail in slug: return p
                return price['default']
            return price

    # Check Categories
    if 'butter' in ingredient: return PRICE_MAP['categories']['butter']
    if 'extract' in ingredient: return PRICE_MAP['categories']['extract']
    if any(n in ingredient for n in ['pecan', 'walnut', 'almond', 'nut']): return PRICE_MAP['categories']['nuts']
    if 'oil' in ingredient: return PRICE_MAP['categories']['oil_olive']
    if 'sugar' in ingredient: return PRICE_MAP['staples']['sugar']
    if 'flour' in ingredient: return PRICE_MAP['staples']['flour']
    if 'cornstarch' in ingredient: return PRICE_MAP['staples']['cornstarch']

    return PRICE_MAP['staples']['default']

def augment_data():
    # Load Files
    try:
        with open('view_inventory.json', 'r') as f: inv_data = json.load(f)
        with open('view_purchases.json', 'r') as f: pur_data = json.load(f)
    except FileNotFoundError as e:
        print(f"Error: Ensure view_inventory.json and view_purchases.json are in this folder. {e}")
        return

    inv_count = 0
    pur_count = 0

    # Process Inventory (unit_cost = Package Price)
    for rec in inv_data['records']:
        price = get_seed_price(rec)
        rec['unit_cost'] = price
        inv_count += 1

    # Process Purchases
    # unit_price = Package Price
    # total_cost = quantity_purchased * unit_price
    for rec in pur_data['records']:
        price = get_seed_price(rec)
        qty = rec.get('quantity_purchased', 1)
        rec['unit_price'] = price
        rec['total_cost'] = float(qty) * price
        pur_count += 1

    # Save Augmented Files
    with open('view_inventory_augmented.json', 'w') as f:
        json.dump(inv_data, f, indent=2)
    with open('view_purchases_augmented.json', 'w') as f:
        json.dump(pur_data, f, indent=2)

    print(f"Success! Augmented {inv_count} inventory records and {pur_count} purchase records.")
    print("Created 'view_inventory_augmented.json' and 'view_purchases_augmented.json'")

if __name__ == "__main__":
    augment_data()
